alter table UNTITLED_VETERINARIAN add constraint FK_UNTITLED_VETERINARIAN_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_UNTITLED_VETERINARIAN_ON_USER on UNTITLED_VETERINARIAN (USER_ID);
