alter table INFORPRO_VETERINARIAN add constraint FK_INFORPRO_VETERINARIAN_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_INFORPRO_VETERINARIAN_ON_USER on INFORPRO_VETERINARIAN (USER_ID);
