alter table INFORPRO_VISIT add constraint FK_INFORPRO_VISIT_ON_PET foreign key (PET_ID) references INFORPRO_PET(ID);
alter table INFORPRO_VISIT add constraint FK_INFORPRO_VISIT_ON_VETERINARIAN foreign key (VETERINARIAN_ID) references INFORPRO_VETERINARIAN(ID);
create index IDX_INFORPRO_VISIT_ON_PET on INFORPRO_VISIT (PET_ID);
create index IDX_INFORPRO_VISIT_ON_VETERINARIAN on INFORPRO_VISIT (VETERINARIAN_ID);
