-- begin INFORPRO_VISIT
alter table INFORPRO_VISIT add constraint FK_INFORPRO_VISIT_ON_PET foreign key (PET_ID) references INFORPRO_PET(ID)^
alter table INFORPRO_VISIT add constraint FK_INFORPRO_VISIT_ON_VETERINARIAN foreign key (VETERINARIAN_ID) references INFORPRO_VETERINARIAN(ID)^
create index IDX_INFORPRO_VISIT_ON_PET on INFORPRO_VISIT (PET_ID)^
create index IDX_INFORPRO_VISIT_ON_VETERINARIAN on INFORPRO_VISIT (VETERINARIAN_ID)^
-- end INFORPRO_VISIT
-- begin INFORPRO_VETERINARIAN
alter table INFORPRO_VETERINARIAN add constraint FK_INFORPRO_VETERINARIAN_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_INFORPRO_VETERINARIAN_ON_USER on INFORPRO_VETERINARIAN (USER_ID)^
-- end INFORPRO_VETERINARIAN
-- begin INFORPRO_PET
alter table INFORPRO_PET add constraint FK_INFORPRO_PET_ON_TYPE foreign key (TYPE_ID) references INFORPRO_PET_TYPE(ID)^
alter table INFORPRO_PET add constraint FK_INFORPRO_PET_ON_OWNER foreign key (OWNER_ID) references INFORPRO_OWNER(ID)^
create index IDX_INFORPRO_PET_ON_TYPE on INFORPRO_PET (TYPE_ID)^
create index IDX_INFORPRO_PET_ON_OWNER on INFORPRO_PET (OWNER_ID)^
-- end INFORPRO_PET
-- begin INFORPRO_CONSUMABLE
create unique index IDX_INFORPRO_CONSUMABLE_UK_TITLE on INFORPRO_CONSUMABLE (TITLE) where DELETE_TS is null ^
-- end INFORPRO_CONSUMABLE
-- begin INFORPRO_VISIT_CONSUMABLE_LINK
alter table INFORPRO_VISIT_CONSUMABLE_LINK add constraint FK_VISCON_ON_CONSUMABLE foreign key (CONSUMABLE_ID) references INFORPRO_CONSUMABLE(ID)^
alter table INFORPRO_VISIT_CONSUMABLE_LINK add constraint FK_VISCON_ON_VISIT foreign key (VISIT_ID) references INFORPRO_VISIT(ID)^
-- end INFORPRO_VISIT_CONSUMABLE_LINK
