-- begin UNTITLED_PET
alter table UNTITLED_PET add constraint FK_UNTITLED_PET_ON_TYPE foreign key (TYPE_ID) references UNTITLED_PET_TYPE(ID)^
alter table UNTITLED_PET add constraint FK_UNTITLED_PET_ON_OWNER foreign key (OWNER_ID) references UNTITLED_OWNER(ID)^
create index IDX_UNTITLED_PET_ON_TYPE on UNTITLED_PET (TYPE_ID)^
create index IDX_UNTITLED_PET_ON_OWNER on UNTITLED_PET (OWNER_ID)^
-- end UNTITLED_PET
-- begin UNTITLED_VISIT
alter table UNTITLED_VISIT add constraint FK_UNTITLED_VISIT_ON_PET foreign key (PET_ID) references UNTITLED_PET(ID)^
alter table UNTITLED_VISIT add constraint FK_UNTITLED_VISIT_ON_VATERINARIAN foreign key (VATERINARIAN_ID) references UNTITLED_VETERINARIAN(ID)^
create index IDX_UNTITLED_VISIT_ON_PET on UNTITLED_VISIT (PET_ID)^
create index IDX_UNTITLED_VISIT_ON_VATERINARIAN on UNTITLED_VISIT (VATERINARIAN_ID)^
-- end UNTITLED_VISIT
-- begin UNTITLED_CONSUMABLE
create unique index IDX_UNTITLED_CONSUMABLE_UK_TITLE on UNTITLED_CONSUMABLE (TITLE) where DELETE_TS is null ^
-- end UNTITLED_CONSUMABLE
-- begin UNTITLED_VETERINARIAN
alter table UNTITLED_VETERINARIAN add constraint FK_UNTITLED_VETERINARIAN_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_UNTITLED_VETERINARIAN_ON_USER on UNTITLED_VETERINARIAN (USER_ID)^
-- end UNTITLED_VETERINARIAN
-- begin UNTITLED_VISIT_CONSUMABLE_LINK
alter table UNTITLED_VISIT_CONSUMABLE_LINK add constraint FK_VISCON_ON_VISIT foreign key (VISIT_ID) references UNTITLED_VISIT(ID)^
alter table UNTITLED_VISIT_CONSUMABLE_LINK add constraint FK_VISCON_ON_CONSUMABLE foreign key (CONSUMABLE_ID) references UNTITLED_CONSUMABLE(ID)^
-- end UNTITLED_VISIT_CONSUMABLE_LINK
